import { Space_Mono } from 'next/font/google';
import './globals.css';

import UserProvider from '@/contexts/UserContext';

const space_mono = Space_Mono({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// =============================
export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark'>
      <body className={space_mono.className}>
        <UserProvider>
          <div className='flex justify-center min-h-screen text-slate-950 dark:text-white bg-slate-100 dark:bg-slate-900'>
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
